### ISSUE TITLE
openjdk: Packages needs to be updated to latest version

### ISSUE THREAD

**Issue by vnepogodin** [CachyOS/CachyOS-PKGBUILDS#128]
diff against arch repos:
jdk-openjdk. '21.0.2.u13-2' > '21.u35-10'
jdk17-openjdk. '17.0.10.u7-1' > '17.0.9.u8-4'

**Comment by ventureoo** [comment]
Done with https://github.com/CachyOS/CachyOS-PKGBUILDS/commit/246cb4fcaae8699145c3226b1a6b47b8c2a70e67.
