### ISSUE TITLE
Is `uksmd` still a necessary dependency for `cachyos-settings`?

### ISSUE THREAD

**Issue by dirk-hub** [CachyOS/CachyOS-PKGBUILDS#203]
https://github.com/CachyOS/CachyOS-PKGBUILDS/blob/e553569244812fbc813b472070f2ab9135cc69b2/cachyos-settings/PKGBUILD#L19

Uninstalling `uksmd-git` aka `uksmd` is currently not possible because `cachyos-settings` has a dependency on it:
```
$ sudo pacman -R uksmd-git 
checking dependencies...
error: failed to prepare transaction (could not satisfy dependencies)
:: removing uksmd-git breaks dependency 'uksmd' required by cachyos-settings
```

Seeking through the repo of `cachyos-settings` I however found no reference to `uksmd` so I wonder if there actually is no depencendy on it.

To be able to remove the package `uksmd-git` without uninstalling `cachyos-settings`, latter must not be dependent on former anymore.

As I found no need for this dependency, maybe it could be removed from this `PKGBUILD`.

References:
https://github.com/CachyOS/CachyOS-Settings
https://github.com/CachyOS/uksmd

**Comment by ptr1337** [comment]
Hi,
yes it is. But you can do following to avoid enabled uksmd, when cachyos-settings packages gets a update.

```
sudo systemctl disable --now uksmd.service
# Dont enable at cachyos-settings update
sudo systemctl mask uksmd.service

```
This will block uksmd from updating/loading or equal.

**Comment by ptr1337** [comment]
> As I found no need for this dependency, maybe it could be removed from this PKGBUILD

No, we can not do that, since otherwise users won't get this at the installation. This is thought for our users - and if there problems with the settings, you can simply mask it as above.
Same counts for zram config for example - you can create locally just a higher zram.conf, which will overwrite the existing one.

**Comment by dirk-hub** [comment]
> > As I found no need for this dependency, maybe it could be removed from this PKGBUILD
> 
> No, we can not do that, since otherwise users won't get this at the installation. This is thought for our users - and if there problems with the settings, you can simply mask it as above. Same counts for zram config for example - you can create locally just a higher zram.conf, which will overwrite the existing one.

I understand `uksmd` is considered a default component for an installation on CachyOS - just like several `cachyos-*` packages are.

Making it a dependency of `cachyos-settings` however has the effect `uksmd` cannot be removed from the system.

If it is considered a base block of CachyOS, why not install it on the installation time and just mark it manually installed, so it can be uninstalled but by default it is installed on new systems.

I think I don't understand the reasoning of making a full blown service a dependency of a "settings" package in the first place.

**Comment by ptr1337** [comment]
Dirk, the uksmd packages has in size 55 KiB.
This is really not something, which really bloat your system in any way. The dependecies, which uksmd needs are anyways installed  anyways.

Splitting it would make it for our installation very problematic and also can not be just done "ondemand".

**Comment by ptr1337** [comment]
Ill close here. Masking the service will do it.

**Comment by ptr1337** [comment]
uksmd wont be required with upcoming cachyos-settings release.

**Comment by dirk-hub** [comment]
Thank you, the change looks reasonable to me.
