### ISSUE TITLE
Gaming Meta should include `vulkan-tools` 

### ISSUE THREAD

**Issue by mainrs** [CachyOS/CachyOS-PKGBUILDS#263]
When creating automated system data for Lutris in the case of bugs (via `lutris --submit-issue`), the program relies on `vulkaninfo` to gather some information.

**Comment by ptr1337** [comment]
It appears this is already an optdepend by lutris

**Comment by mainrs** [comment]
I can only tell that I did not get prompted to install any optional dependencies. I just think that, since the tool is required for debugging purposes when hitting issues using Lutris, it might be worth to install by default.

**Comment by 1Naim** [comment]
Optional dependencies are only listed. You still have to go out of your way to install it manually.

**Comment by mainrs** [comment]
> Optional dependencies are only listed. You still have to go out of your way to install it manually.

I know. I was just hoping to reduce friction for users in general. I get the gist that CachyOS is Arch-based, so it is somewhat expected to have more Linux knowledge and know how Arch package management works.

But since the gaming meta is a package set, I was hoping to reduce issues for newcomers and users in general. It's a small change that simply enhances UX for everybody.

I am willing to open the PR. Just let me know!

**Comment by ptr1337** [comment]
https://github.com/CachyOS/CachyOS-PKGBUILDS/commit/bfad0891e7d06977bacd32322626fb2ec86f9b27

Fixed
