### ISSUE TITLE
hyprland: Hyprland is broken because the dependency hyprutils was not upgraded

### ISSUE THREAD

**Issue by cassiofb-dev** [CachyOS/CachyOS-PKGBUILDS#285]
Hi, good night. Thanks for this project, dunno if here is the right place to open a package issue.

There was a upgrade on hyprland today and some of its dependencies were not updated with the main package. I can confirm other people got the same issue as me. One strange thing is that the discord bot said the build was sucessful but the upgrade didn't arrive for the end users.

- Discord bot message: https://discord.com/channels/862292009423470592/1222990058135752815/1272934159685390366
- https://archlinux.org/packages/extra/x86_64/hyprland/
- https://archlinux.org/packages/extra/x86_64/hyprutils/

What I have tried:

- I tried first just run "paru"
- Tried to upgrade with "pacman -Syu"
- And cleaned the cache to try the commands above again "paru -Sc"

**Comment by cassiofb-dev** [comment]
The upgrade didn't work even tho the bot said it was ok.

![image](https://github.com/user-attachments/assets/6b4155dd-959e-4a38-8af3-05956f3b16e6)

**Comment by cassiofb-dev** [comment]
As a temporary workaround users can run "paru hyprutils" on the terminal and pick the extra package instead of cachyos repos:

![IMG_20240813_224717](https://github.com/user-attachments/assets/2012b64d-135d-4283-bd0a-c48457bb3378)

**Comment by ptr1337** [comment]
Fixed
