### ISSUE TITLE
[RFC] Investigate into optimizing "llvm" PKGBUILD with PGO

### ISSUE THREAD

**Issue by ptr1337** [CachyOS/CachyOS-PKGBUILDS#321]
The arch's LLVM toolchain is using dynamic linking and therefore it is pretty slow, which can be found here as a benchmark: https://github.com/ptr1337/llvm-bolt-scripts/blob/master/results.md (Stage 1 was the arch toolchain)

The libllvm.so is invoked from several compilers, like Clang, Rust and likely also from the llvmpipe and others.
We should investigate, if it is worth to optimize the "llvm" package with PGO and if it brings benefits.

**Comment by 1Naim** [comment]
Is it also worth building an optimized package of clang? like what we are doing with gcc

**Comment by ptr1337** [comment]
> Is it also worth building an optimized package of clang? like what we are doing with gcc

Ive straced building with Clang ones, and the main calls were done with "libllvm.so", due its dynamic linking.

**Comment by ptr1337** [comment]
Results building Clang with the measure_build.s script:

```
optimized 6.11rc5:
real    3m53,965s
user    116m4,862s
sys     3m7,756s

default 6.11rc5:
real    4m11,728s
user    125m6,363s
sys     3m11,283s
```

**Comment by 1Naim** [comment]
A user has also noticed faster build times with PGO'd LLVM.
```
clang + ThinLTO kernel
WIth PGO -> 8m 23s  
Without PGO -> 8m 42s
```
