### ISSUE TITLE
I believe that xorg-xwayland is optional for hyprland

### ISSUE THREAD

**Issue by user451421541757324** [CachyOS/CachyOS-PKGBUILDS#37]
I installed hyprland from the CachyOS repos without xorg-xwayland (on KDE live) this way: `sudo pacman -Syy hyprland --asume-installed xorg-xwayland` and it started without problems, so I _believe_ that xorg-xwayland should be an optional dependency.

**Comment by ventureoo** [comment]
Isn't xorg-xwayland already an optional dependency for wlroots?

**Comment by user451421541757324** [comment]
I'm not sure:
![Screenshot](https://user-images.githubusercontent.com/109753483/223692737-ff8bd2d1-34d5-4d37-abc4-334f55ee0acf.png)

**Comment by vnepogodin** [comment]
No. It should be required dependency because it is enabled by default, and without xwayland you will have programs that will never start because they are still apps that doesnt work in native mode nor support wayland

**Comment by vnepogodin** [comment]
Actually better to use `hyprland-git` instead of `hyprland` as its recommended by hyprland to use that way
We provide `hyprland-git` in our repositories

**Comment by user451421541757324** [comment]
> without xwayland you will have programs that will never start because they are still apps that doesnt work in native mode nor support wayland

I believe that, thanks to Qt5 and GTK3, today there are more programs that work on Wayland than those that don't. So, it's not difficult to have a pure wayland setup.

But that's okay, I'll just use an alias of  pacman with `--asume-installed` and the problem is solved.

>We provide hyprland-git in our repositories

Missed that, thank you!
