### ISSUE TITLE
wine-cachyos: enable optical flow patches

### ISSUE THREAD

**Issue by silvanshade** [CachyOS/CachyOS-PKGBUILDS#401]
Would it be possible to enable the same optical flow patches from `proton-cachyos` for `wine-cachyos`?

It would be nice to be able to try frame generation with games from egs under lutris, for example.

I tried to do this myself but didn't manage to make it work.

What I tried:

1. Apply `proton-cachyos/wine-optical-flow.patch` to `wine-cachyos`.
2. Build and install modified `wine-cachyos`.
3. Apply symlinks to link cachy dxvk / nvapi / vkd3d (with optical flow patches) into lutris runners (from https://github.com/CachyOS/CachyOS-Welcome/issues/78#issue-2471553563)
4. Select Wine 9.0 staging (wine-cachyos) runner in lutris, then under advanced "Graphics" select `proton-cachyos` for dxvk, vkd3d, nvapi versions

This allows launching games without issue but frame generation is not detected.

I'm guessing at least part of the problem is it is missing the equivalent last step from `proton-cachyos/proton-optical-flow.patch` which copies the new `nvofapi{,64}.dll` files into the system prefixes.

But I don't know where to do that for `wine-cachyos`.

I also did try just selecting `proton-cachyos` as the runner (after the symlinks) but that causes egs to immediately crash to the bug report dialog, so that probably won't work as a solution.

**Comment by ptr1337** [comment]
Hi,

Yes, this will be done automatcially together with the upcoming experimental rebase for wine-cachyos:
https://github.com/CachyOS/wine-cachyos/

@loathingKernel will add this as soon he will do the rebase :)

Currently you can also workaround with symlinking proton-cachyos directly into lutrs:
```sh
#!/bin/bash

echo "Symlinking proton-cachyos"
mkdir ~/.local/share/lutris/runners/wine/proton-cachyos
ln -s /usr/share/steam/compatibilitytools.d/proton-cachyos/files/*  ~/.local/share/lutris/runners/wine/proton-cachyos

echo "DXVK Cachy"

mkdir -p ~/.local/share/lutris/runtime/dxvk/proton-cachyos/x32
mkdir -p ~/.local/share/lutris/runtime/dxvk/proton-cachyos/x64
ln -s /usr/share/steam/compatibilitytools.d/proton-cachyos/files/lib/wine/dxvk/* ~/.local/share/lutris/runtime/dxvk/proton-cachyos/x32
ln -s /usr/share/steam/compatibilitytools.d/proton-cachyos/files/lib64/wine/dxvk/* ~/.local/share/lutris/runtime/dxvk/proton-cachyos/x64

echo "NVAPI Cachy"

mkdir -p ~/.local/share/lutris/runtime/dxvk-nvapi/proton-cachyos/x32
mkdir -p ~/.local/share/lutris/runtime/dxvk-nvapi/proton-cachyos/x64
ln -s /usr/share/steam/compatibilitytools.d/proton-cachyos/files/lib/wine/nvapi/* ~/.local/share/lutris/runtime/dxvk-nvapi/proton-cachyos/x32
ln -s /usr/share/steam/compatibilitytools.d/proton-cachyos/files/lib64/wine/nvapi/* ~/.local/share/lutris/runtime/dxvk-nvapi/proton-cachyos/x64

echo "VKD3D Cachy"

mkdir -p ~/.local/share/lutris/runtime/vkd3d/proton-cachyos/x86
mkdir -p ~/.local/share/lutris/runtime/vkd3d/proton-cachyos/x64

ln -s /usr/share/steam/compatibilitytools.d/proton-cachyos/files/lib/wine/vkd3d-proton/* ~/.local/share/lutris/runtime/vkd3d/proton-cachyos/x86
ln -s /usr/share/steam/compatibilitytools.d/proton-cachyos/files/lib64/wine/vkd3d-proton/* ~/.local/share/lutris/runtime/vkd3d/proton-cachyos/x64
```

Having it in wine-cachyos would be the more proper way, but should come soon. :)

**Comment by loathingKernel** [comment]
I would much prefer to make proton-cachyos compatible with umu in the case of Lutris.

**Comment by silvanshade** [comment]
Thanks for the responses. I will go ahead and close this then.

Also, I noticed that I can use proton-cachyos without problems through heroic launcher unlike lutris so that's a good enough solution for me.
