### ISSUE TITLE
gnome-shell patches

### ISSUE THREAD

**Issue by dougg0k** [CachyOS/CachyOS-PKGBUILDS#421]
Hi,

As you have a mutter-cachyos, maybe a gnome-shell with patches would also help improve things.

Ref: https://aur.archlinux.org/packages/gnome-shell-performance

**Comment by 1Naim** [comment]
Did you even check the PKGBUILD for that AUR package? It doesn't have any cherrypicked patches.

**Comment by dougg0k** [comment]
Maybe make it available, not by default till people can test it enough and report bugs. Be on a diff mirror or not.
