### ISSUE TITLE
O3 or Ofast for ffmpeg?

### ISSUE THREAD

**Issue by firasuke** [CachyOS/CachyOS-PKGBUILDS#44]
https://github.com/CachyOS/CachyOS-PKGBUILDS/blob/ac05c8375bc1c5c878d1b7d98017c3128424a3cb/ffmpeg/PKGBUILD#L130

Upon reading this, I've noticed that you're specifying both optimization flags, I understand that GCC will process the latter, but is `Ofast` intended for use with `ffmpeg`?

**Comment by ptr1337** [comment]
This is actually picked from clearlinux:

https://github.com/clearlinux-pkgs/not-ffmpeg/blob/main/not-ffmpeg.spec#L127

Basically if -Ofast is set, -O3 will be ignored in the end.

**Comment by oech3** [comment]
Is `-Ofast` really safe?
