### ISSUE TITLE
Can you remove wdisplays depend of wayfire-desktop-git?

### ISSUE THREAD

**Issue by jacky-lau-1** [CachyOS/CachyOS-PKGBUILDS#45]
Because wcm has wdisplays allready, when the user install wayfire-desktop-git, wcm and wdisplays get conflicting.

**Comment by vnepogodin** [comment]
Sure
Pushed commit with removal: https://github.com/CachyOS/CachyOS-PKGBUILDS/commit/4f343a065e0dc0ffa904744a4056ed22cf944293

Many thanks!
